#!/usr/bin/env bash

MASON_COMMAND=$1 ; shift
MASON_NAME=$1 ; shift
MASON_VERSION=$1 ; shift

set -eu
set -o pipefail

MASON_RELEASED_VERSION="0.18.0"

if [ "${MASON_COMMAND}" = "--version" ]; then
    echo ${MASON_RELEASED_VERSION}
    exit 0
fi

function usage {
    echo "Usage: $0 <command> <lib> <version>"
}

if [ -z "${MASON_COMMAND}" ]; then
    usage
    exit 1
fi

ROOTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null && pwd )"

if test -L "$ROOTDIR/mason"; then
    ROOTDIR="$(dirname "$(readlink "$ROOTDIR/mason")")"
fi

MASON_DIR=${MASON_DIR:-$ROOTDIR}

if [ "${MASON_COMMAND}" = "env" ]; then
    . ${MASON_DIR}/mason.sh > /dev/null
    eval echo \$${MASON_NAME}
    exit
fi

if [ -z "${MASON_NAME}" ]; then
    usage
    echo "Missing <lib>"
    exit 1
elif [ -z "${MASON_VERSION}" ]; then
    usage
    echo "Missing <version>"
    exit 1
fi

if [ "${MASON_COMMAND}" = "trigger" ]; then
    if [ -z "${MASON_TRAVIS_TOKEN}" ]; then
        echo "MASON_TRAVIS_TOKEN is not set."
        exit 1
    fi

    config=$(ruby <<RUBY
    require 'yaml'
    require 'json'
    config = YAML.load_file("scripts/${MASON_NAME}/${MASON_VERSION}/.travis.yml")
    config["env"] ||= {}
    config["env"]["global"] ||= []
    config["env"]["global"] << "MASON_NAME=${MASON_NAME}" << "MASON_VERSION=${MASON_VERSION}"
    puts JSON.pretty_generate(config)
RUBY
    )

    body="{
      \"request\": {
        \"message\": \"Building ${MASON_NAME} ${MASON_VERSION}\",
        \"branch\": \"$(git rev-parse --abbrev-ref HEAD)\",
        \"config\": ${config}
      }
    }"


    # ensure this works:
    # curl https://circleci.com/api/v1.1/me?circle-token=${CIRCLE_API_TOKEN}
    CIRCLE_VCS_TYPE="github"
    CIRCLE_USERNAME="mapbox"
    CIRCLE_PROJECT="mason"
    CIRCLE_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
    CIRCLE_JOB="build-linux"

    curl -s -X POST \
      -d build_parameters[CIRCLE_JOB]=${CIRCLE_JOB} \
      -u ${CIRCLE_API_TOKEN}: \
      -H "Accept: application/json" \
      https://circleci.com/api/v1.1/${CIRCLE_VCS_TYPE}/${CIRCLE_USERNAME}/${CIRCLE_PROJECT}/tree/${CIRCLE_BRANCH}

    exit
fi

. ${MASON_DIR}/mason.sh

export MASON_DIR
if [ -d "${MASON_DIR}/scripts/${MASON_NAME}/${MASON_VERSION}-${MASON_PLATFORM_VERSION}" ]; then
    bash "${MASON_DIR}/scripts/${MASON_NAME}/${MASON_VERSION}-${MASON_PLATFORM_VERSION}/script.sh" "${MASON_COMMAND}" "$@"
else
    bash "${MASON_DIR}/scripts/${MASON_NAME}/${MASON_VERSION}/script.sh" "${MASON_COMMAND}" "$@"
fi
